config/routes.rb
Rails.application.routes.draw do

	get '/forms', to: 'static_pages#forms'

	get '/staff', to: 'static_pages#staff'

	get '/location', to: 'static_pages#location'

	root 'static_pages#home'

	resources :contacts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name, presence: true, length: {maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
	format: { with: VALID_EMAIL_REGEX }
  	validates :subject, presence: true, length: {maximum:50}
  	validates :body, presence: true, length: {maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)
    	if @contact.save
    	  flash[:success] = "Thank you for your message. We will get back to you shortly."
          ContactMailer.contact_email(@contact).deliver
    	  redirect_to root_url
    	else
      	render 'new'
    	end
	end

	private 
  	def contact_params
  		params.require(:contact).permit(:name, :subject, :email, :body)                       
 	 end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

	def location
	end

	def forms
	end

	def staff
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/new.html.erb
<div class = 'content-section'>
	<div class = 'text-center'>
		<h1> Contact </h1>
	</div>
	<br>
	<div class = 'text-center'>
		<h3>Phone: (585) 658-4180</h3>
		<h3>Fax: (585) 658-2850</h3>
	</div>
	<br>
	<div id = 'form-container'>
		<h2 class = 'text-center'>Leave a Message</h2>
		<br>
	<%= form_for(@contact, :url => { :action => "create" , :anchor => "form-container" }) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.label :name %>
	     <%= f.text_field :name, class: 'form-control' %>
	     <br>
	     <%= f.label :email %>
	     <%= f.email_field :email, class: 'form-control' %>
	     <br>
	     <%= f.label :subject %>
	     <%= f.text_field :subject, class: 'form-control' %>
	     <br>
	      <%= f.label :body %>
	      <%= f.text_area :body, class: 'form-control' %>

	      
     		
	      <br>
	     <div class = 'text-center' id = 'feedback-button'>
	   		<%= f.button :Submit, :class=> "btn btn-primary", :id=> "feedback-button" %>
	   	</div>
	   
	  <% end %>
	</div>

</div>

app/views/layouts/_footer.html.erb
<div class = 'credit-footer fixed-bottom'>
	Created by <a href = 'http://www.alexanderchichester.com'>Alex Chichester</a>
	<a href = 'https://www.facebook.com/Dr-Theresa-Alianell-192547087459794/'>
		<%=image_tag('facebook.png', id: 'facebook-logo')%>
	</a>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class = 'container fixed-top' id = 'banner'>
	<%= link_to root_path do %>
	<div id = 'logo'>
		<img src="https://fontmeme.com/permalink/170715/b416d5f50b7c82664031261f9cd73d92.png" alt="calligraphy-fonts" border="0" id = 'text-logo'>
		<em><h4 id = 'chiropractor'>chiropractor</h4></em>
	</div>
	<% end %>


	<div class = 'container' id = 'info'>
		<h3>6416 Sonyea Rd. (RT 36)</h3>
		<h3>Mt. Morris, NY 14510 </h3>
		<br>
		<h3> Phone: (585) 658-4180 </h3>
		<h3> Fax: (585) 658-2850</h3>
	</div>
</div>

app/views/layouts/_sidebar.html.erb
<ul class="sidenav">
  <li><%=link_to "Home", root_path %></li>
  <li><%=link_to "Location", location_path %></li>
  <li><%=link_to "Staff", staff_path %></li>
  <li><%=link_to "Patient Forms", forms_path%></li>
  <li><%=link_to "Contact", new_contact_path%></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Theresa Alianell</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Cinzel:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	   <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
	  	<%= render 'layouts/header' %>
	  	<%= render 'layouts/sidebar' %>
	    <%= yield %>
    	<%= render 'layouts/footer' %>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/forms.html.erb
<div class = 'content-section'>
	<div class = 'text-center'>
		<h1>Patient Forms</h1>
	</div>
	<br>
	<div id = 'patient-form-container'>
		<h3>To speed up your visit, print and fill out the following form and bring it to your appointment:</h3>
		<br>
		
		&#8226<%= link_to " Confidential Patient Case History", asset_path("patient_forms.pdf")%>
		
	</div>
</div>

app/views/static_pages/home.html.erb
<div class = 'content-section'>
	<div id = 'main-image' class = 'text-center'>
		<%= image_tag('house.jpg', :id => "house-image")%>
	</div>
	<br>
	<div class = 'text-center'>
		<h2> Hours </h2>
		<br>
		<table class = 'table table-striped' id = 'hours-table'>
			<tr><th>Monday</th><td>9am - 1pm  &  3pm - 7pm</td></tr>
			<tr><th>Tuesday</th><td>8am - 12pm</td></tr>
			<tr><th>Wednesday</th><td>9am - 1pm  &  3pm - 7pm</td></tr>
			<tr><th>Thursday</th><td>9am - 1pm</td></tr>
			<tr><th>Friday</th><td>9am - 1pm  &  3pm - 7pm</td></tr>
			<tr><th>Saturday</th><td>9am - 1pm</td></tr>
			<tr><th>Sunday</th><td>Closed</td></tr>
		</table>
	</div>
</div>

app/views/static_pages/location.html.erb
<div class = 'content-section'>
	<div class = 'text-center'>
		<iframe frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ0z1Y3hFj0YkRj8qUKP-0YZY&key=AIzaSyDQpfXw0TpakURxlUVlHZrGQyYvtdb6ebs" allowfullscreen></iframe>
	</div>
</div>

app/views/static_pages/staff.html.erb
<div class = 'content-section'>
	<div class = 'text-center'>
		<h1> Our Staff </h1>
	</div>
	<br>

	<div class = 'staff-container'>
		<div class = 'staff-item'>
			<h4> Dr. Theresa E. Alianell</h4>
			
			<%= image_tag('theresa.jpg', :class => "staff-image")%>
			
			<div class = 'staff-description'>
				<p>Dr. Theresa graduated from Life Chiropractic College in March of 1990.  She practiced in Bristol Tennessee until October 1995 and opened an office in Mount Morris November 1995.  Gonstead diversified is her main adjusting technique, but she uses several different types of adjusting moves.   She fits the adjustment to the patient!  The practice originally was on Chapel Street but is now on route 36 just outside the village.  When not adjusting patients she can be found kayaking the lakes or hiking the finger lakes trail.<p>
			</div>
		</div>
	</div>
	<br>
	<div class = 'staff-container'>
		<div class = 'staff-item'>
			<h4> Ellen Carlock</h4>
			<%= image_tag('ellen.jpg', :class => "staff-image")%>
			<div class = 'staff-description'>
				<p>Ellen has been working with Dr. Theresa since 2004.  She has 4 wonderful children and 2 fabulous grandchildren.  Ellen manages the administrative aspects of the office.  She is in charge of a large share of the insurance billing. If you have a question about the running of the office or your blue cross/blue shield give her a call!<p>
			</div>
		</div>
	</div>
	<br>
	<div class = 'staff-container'>
		<div class = 'staff-item'>
			<h4>Jenny Leslie</h4>
			<%= image_tag('jenny.jpeg', :class => "staff-image")%>
			<div class = 'staff-description'>
				<p>Jenny has been working with Dr. Theresa since 2006. She is married and has 2 beautiful daughters and 3 handsome grandsons.  Jenny is in charge of records and medicare billing.  If you have any questions regarding either one of these things give her a call!<p>
			</div>
		</div>
	</div>
</div>